[package]
name = "claymore"
version = "0.1.0"
edition = "2018"

[lib]
name = "claymore"
path = "src/lib.rs"

[dependencies]
base64 = "0.13.0"
crc = "2.0"
quick-xml = { version = "0.21", features = [ "serialize" ] }
rand = "0.8.0"
serde = { version = "1.0", features = [ "derive" ] }
